`plotly` ROC and precision-recall curves (#253)
* mv pymatviz/(relevance.py->classify/curves_matplotlib).py

* add classify/curves_plotly.py with roc_curve_plotly() and precision_recall_curve_plotly()

* mv assets/scripts/relevance/* to assets/scripts/classify/* and add plotly demos

* show plotly demos in readme

* mv tests/(test_relevance -> classify/test_curves_matplotlib.py)

* add tests for classify/curves_plotly.py

* remove line breaks in assets/svg/roc-curve.svg

* fix mypy error classify/confusion_matrix.py:13: error: Module not callable