Add `pymatviz.io.df_to_svg` (#179)
* add pymatviz.io.df_to_svg

* add test_io.test_df_to_svg

* breaking: change Key.model_params value model_parameters->model_params

* prefer less-secure std lib xml over defusedxml to avoid another dep

* add optional dep cssutils

* add optional dep bs4

* add optional dep lxml

* accommodate slightly different width/height values in CI

FAILED tests/test_io.py::test_df_to_svg[False-14-False-457.775pt-875.174687pt] - AssertionError: assert '457.525pt' == '457.775pt'

  - 457.775pt
  ?     ^^
  + 457.525pt
  ?     ^^
FAILED tests/test_io.py::test_df_to_svg[True-18-True-559.275pt-1121.110312pt] - AssertionError: assert '559.525pt' == '559.275pt'

  - 559.275pt
  ?      -
  + 559.525pt
  ?     +
FAILED tests/test_io.py::test_df_to_svg[False-10-True-357.275pt-629.239062pt] - AssertionError: assert '357.15pt' == '357.275pt'

  - 357.275pt
  ?     ^^
  + 357.15pt
  ?     ^
============ 3 failed, 640 passed, 15 skipped in 182.33s (0:03:02) =============

* only expect reduced SVG size if svgo in PATH