Support `phonopy` `TotalDos` and `BandStructure` in `phonon_dos` and `phonon_bands` plots (#256)
* accept phonopy.dos.TotalDos or dict of them as input to phonon_dos()

* add phonopy yaml example to assets/scripts/phonons/phonon_dos.py

* add test_phonon_dos_phonopy

* move Key attributes label, description, to key.yml for use outside python

add (math) symbol to some Keys

* remove rarely used LabelEnum methods and their tests

key_val_dict
val_label_dict
val_desc_dict
label_desc_dict

* more Key enum tests

* support phonopy BandStructures in phonon_bands() via new helper phonopy_to_pymatgen_bands

* add test_phonon_bands_with_phonopy

* fix phonons.py into phonons/plotly.py and phonons/helpers.py

* split test_phonons.py into test_helpers.py and test_plotly.py

* fix mypy crash due to name clash in subfolders

* keys.yml reduce whitespace

* phonon scripts fix ModuleNotFoundError: No module named 'atomate2'

  File "/home/runner/work/pymatviz/pymatviz/assets/scripts/phonons/phonon_dos.py", line 23, in <module>
    docs[key] = json.loads(file.read(), cls=MontyDecoder)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/monty/json.py", line 872, in decode
    return self.process_decoded(d)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/monty/json.py", line 769, in process_decoded
    mod = __import__(modname, globals(), locals(), [classname], 0)
ModuleNotFoundError: No module named 'atomate2'

* fix test_keys_yaml_and_enum_are_in_sync

Extra items in the left set: 'yield_'