Fix `ptable_heatmap_splits` `TypeErrors` (#146)
* default PTableProjector colormap to "viridis"

* make LabelEnum inherit from StrEnum

copied from std lib to support older py versions

* try to fix import of `ReprEnum`

* remove import `get_cmap`

* handle and test `dict_values`

* ruff fix FBT001 FBT002

* inline set_vmin_vmax in data_preprocessor

* fix mypy

tests/test_sankey.py:17: error: Too many positional arguments for "sankey_from_2_df_cols"  [misc]
tests/test_utils.py:129: error: Too many positional arguments for "bin_df_cols"  [misc]

* drop ReprEnum for Enum, seems to be pure boilerplate

* remove needless .value from Key.<attr> now that it's a StrEnum

* add more tests for data preprocessor

* refactor data_preprocessor convert values to 1D np.array

TestDataPreprocessor test more data types

* test_unsupported_type error msg

* remove inspect.signature(fmt) hackery

* fix TypeError: test_ptable_heatmap.<locals>.<lambda>() missing 1 required positional argument: '_'

---------

Co-authored-by: Haoyu (Daniel) <yanghaoyu97@outlook.com>